---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  pre_tasks:
    - name: Check docker installation
      command: docker --version
      ignore_errors: true
      register: docker_installed

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed is failed
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
      when: docker_installed is failed

    - name: Create docker network
      docker_network:
        name: app-net
        state: present
  roles: 
    - setup-mongodb  
    - backend-deployment
    - frontend-deployment    